title: OBA-MDCLARA System Integration
description: System integration documentation for OBA and MDCLARA
theme: jekyll-theme-cayman
plugins:
  - jekyll-mermaid
  - jekyll-seo-tag
  - jekyll-feed

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github 