site_name: OBA-MDCLARA Integration Docs
site_url: https://your-username.github.io/obahealthclub
repo_url: https://github.com/your-username/obahealthclub

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasks
  - pymdownx.emoji
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - SSO Concept:
    - Doctors: docs/sso/doctors.md
    - Patients: docs/sso/patients.md
  - System Components:
    - Doctor Profile: docs/components/doctor-profile.md
    - Patient Profile: docs/components/patient-profile.md
  - Data Structures:
    - Doctor Data: docs/data/doctor-data.md
    - Patient Data: docs/data/patient-data.md
  - Integration Flows: docs/integration-flows.md 